### ISSUE TITLE
It does not protect my service - there are a lot of fatal errors

### ISSUE THREAD

**Issue by budarin** [davidmarkclements/overload-protection#4]
I have used the package with koa.js as a middleware.
I see a lot of fatal error in the log: `Server experiencing heavy load: (event loop)`

node version: 15.6.0

**Comment by mcollina** [comment]
That's exactly what this module does. It sheds the load of request it will not be able to server to protect the process health. You see those errors when this module kicks in... essentially you do not have enough compute resources left.

**Comment by budarin** [comment]
Thanks
