### ISSUE TITLE
npm audit failed

### ISSUE THREAD

**Issue by SSANSH** [davidmarkclements/overload-protection#8]
Hi,

npm audit command raise an security error since some day.

`# npm audit report

ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix --force`
Will install overload-protection@1.1.0, which is a breaking change
node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/strip-ansi
    string-width  2.1.0 - 4.1.0
    Depends on vulnerable versions of strip-ansi
    node_modules/string-width
      cli-table3  0.5.0 - 0.5.1
      Depends on vulnerable versions of string-width
      node_modules/cli-table3
        autocannon  3.2.0 - 4.6.0
        Depends on vulnerable versions of cli-table3
        node_modules/autocannon
          overload-protection  >=1.2.0
          Depends on vulnerable versions of autocannon
          node_modules/overload-protection
`
its looks like come from ansi-regex package, can you please provide an update?

**Comment by SSANSH** [comment]
@jonathansamines note you have only to update from "autocannon": "^4.4.1" to  "autocannon": "^7.4.0"

**Comment by mcollina** [comment]
Actually autocannon is a dev dependency, it should be moved there

**Comment by SSANSH** [comment]
is it possibile to move autocannnon to dev dependency and publish a new version of the library.
